# ----------- CONFIGURABLE START -----------
title:            "Thinking as Algorithm"
subtitle:         "Intelligence as a set of algorithms that agents use to adapt to environments."
description:      "Understanding the mind and thoughts in the algorithmic level."
url:              http://ftvision.github.io # Site url, without a slash at the end.
signoff:          "Feitong Yang" # Your name
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Home
    url:          /
    external:     false
  - name:         About me
    url:          /about
    external:     false
  - name:         Software Development
    url:          /swe
    external:     false
  - name:         Reading
    url:          /reading
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

# Markdown Parse and Highligher: gem install kramdown rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge # rougify style <some style> > <some css file>
  parse_block_html: True
  auto_ids: True
