baseURL = "http://example.org/"
DefaultContentLanguage = "zh"
hasCJKLanguage = true
title = "思算｜Thinking as Algorithm"
theme = "ft_personal"
publishDir = "docs"
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 4
[languages]
  [languages.zh]
    title = "思算"
    languageName = "中文"
    weight = 1
  [languages.en]
    title = "Thinking as Algorithm"
    languageName = "English"
    weight = 2
